@echo off
echo Starting MongoDB Service with Administrator privileges...
powershell -Command "Start-Process cmd -ArgumentList '/c net start MongoDB && echo MongoDB started successfully && pause' -Verb RunAs"
